import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GridBackgroundDemo } from "@/app/ui/GridBackground";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative z-10">{children}</div>
        <GridBackgroundDemo />
      </body>
    </html>
  );
}
